// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
Servo* RobotMap::chassisShifterLeft = NULL;
Servo* RobotMap::chassisShifterRight = NULL;
CANJaguar* RobotMap::chassisCANLeftFront = NULL;
CANJaguar* RobotMap::chassisCANRightFront = NULL;
CANJaguar* RobotMap::chassisCANLeftRear = NULL;
CANJaguar* RobotMap::chassisCANRightRear = NULL;
RobotDrive* RobotMap::chassisRobotDrive41 = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	chassisShifterLeft = new Servo(1, 5);
	lw->AddActuator("Chassis", "Shifter Left", chassisShifterLeft);
	
	chassisShifterRight = new Servo(1, 6);
	lw->AddActuator("Chassis", "Shifter Right", chassisShifterRight);
	
	chassisCANLeftFront = new CANJaguar(2);
	
	
	chassisCANRightFront = new CANJaguar(10);
	
	
	chassisCANLeftRear = new CANJaguar(9);
	
	
	chassisCANRightRear = new CANJaguar(16);
	
	
	chassisRobotDrive41 = new RobotDrive(chassisCANLeftFront, chassisCANLeftRear,
              chassisCANRightFront, chassisCANRightRear);
	
	chassisRobotDrive41->SetSafetyEnabled(true);
        chassisRobotDrive41->SetExpiration(0.1);
        chassisRobotDrive41->SetSensitivity(0.5);
        chassisRobotDrive41->SetMaxOutput(1.0);
        chassisRobotDrive41->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
        chassisRobotDrive41->SetInvertedMotor(RobotDrive::kRearRightMotor, true);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
